
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mapping
    username: root
    password: 12345678
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        format_sql: true